spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: "password"
    driverClassName: "org.h2.Driver"
    initialization-mode: always
    continue-on-error: false
  h2:
    console:
      enabled: "true"
  main:
    lazy-initialization: "false"
  devtools:
    restart:
      enabled: "true"
    livereload:
      enabled: "true"